/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockRouterSol from "./MockRouter.sol";
export { MockERC20__factory } from "./MockERC20__factory";
